@Anouncements_HostAddress = https://localhost:7191

GET {{Anouncements_HostAddress}}/weatherforecast/
Accept: application/json

###
POST {{Anouncements_HostAddress}}/weatherforecast/
Content-Type: application/json
Accept: application/json
{ "date": "2025-10-01",
  "temperatureC": 25,
  "summary": "Warm and affordable"
}

###
